### ISSUE TITLE
dot plot to visualise LRI and ER_CELLTYPE together

### ISSUE THREAD

**Issue by Brawni** [CyrilLagger/scDiffCom#1]
Hi!

Great package! I was wondering as per title if there is an easy way to plot LRI and ER_CELLTYPE in the same plot (ideally a dot plot). ORA tables seem to be different per category and I cant see any identifier to map different categories together.

Thank you!

**Comment by CyrilLagger** [comment]
Hi,

Thanks for the interest in the package!

If I understood correctly your question, I don't think there is a way to plot the results of the over-representation test from different categories (e.g. LRI and ER_CELLTYPE) on the same plot. This is because when you perform ORA on, say, the ligand-receptor interactions (LRI) you are aggregating/counting over the cell-type pairs (ER_CELLTYPE), or vice-versa. So there are no ORA results corresponding to a given LRI and a given ER_CELLTYPE at the same time.

This being said, if we forget about ORA for a while, it should be possible to create heatmaps (or dot plots) of the form LRI vs ER_CELLTYPES for specific values attached to each CCI (scores, p-values, logfc, etc). I am not sure how useful that would be and creating a nice plot would require quite some tuning, but just to give you the idea, the following could be a starting point:
```
ggplot(
  GetTableCCI(scdiffcom_object, type = "detected", simplified = TRUE),
  aes(ER_CELLTYPES, LRI, fill = CCI_SCORE_YOUNG)
) + geom_raster(
) + theme(
  axis.text = element_blank()
)
```
where `scdiffcom_object` could be, for example, the object from the [vignette](https://cyrillagger.github.io/scDiffCom/articles/scDiffCom-vignette.html). 

Is that something like that that you had in mind? Do not hesitate to give us more information.

**Comment by Brawni** [comment]
Thanks for your answer! Yes sorry I did realize that and I generated dot plots so all good! 

Thanks!
