### ISSUE TITLE
could not find function "BuildShiny" 

### ISSUE THREAD

**Issue by lef2158** [CyrilLagger/scDiffCom#10]
All of the required libraries are loaded but R cannot find the function "BuildShiny"

**Comment by CyrilLagger** [comment]
Hi, 

Maybe this is because you are using the CRAN version of scDiffCom? Currently, "BuildShiny" is only available from the development version of scDiffCom that can be installed as follows:

`devtools::install_github("CyrilLagger/scDiffCom")`

If that does not fix the problem, can you please send me your `sessionInfo()`?
